### ISSUE TITLE
Documentation Improvement for `react-native-omh-storage`

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-storage#16]
The `react-native-omh-storage` repository currently lacks comprehensive documentation, which is inconsistent with the level of documentation provided in other Open Mobile Hub React Native repositories, such as [react-native-omh-maps](https://github.com/openmobilehub/react-native-omh-maps). 

**Current Situation:**

- The `README.md` file is empty and lacks essential information.
- There are no getting started guides.
- API references are missing.

**Expected Outcome:**

- A detailed `README.md` with:
  - **Introduction:** Brief overview of the library and its purpose.
  - **Getting Started Guide:** Step-by-step instructions on how to install and set up the library.
  - **Usage Examples:** Code examples demonstrating common use cases.
  - **API Reference:** Detailed information about available methods and their parameters.
  - **Contributing Guidelines:** How to contribute to the project.
  - **License Information:** Information about the project's license.

**Request:**

Please provide the same level of documentation consistency as seen in other Open Mobile Hub React Native repositories, specifically the `react-native-omh-maps` repository.

**ETA:**

Could you please provide an estimated timeline for when these documentation improvements might be available?

Thank you for your attention to this matter.

**Comment by adamTrz** [comment]
Hi @dzuluaga we've updated documentation - Readme's, Getting Started and other places have been adjusted and refreshed. Whole documentations is also available [here](https://openmobilehub.github.io/react-native-omh-storage/)

Closing the issue but feel free to reopen if needed 👍
