### ISSUE TITLE
Missing `local.properties` Causes Build Failure with Minimal Guidance

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-storage#54]
When running the app without setting up the `local.properties` file, the following error is generated:

```
WARNING: The option setting 'android.jetifier.ignorelist=jackson-core,fastdoubleparser' is experimental.
5 actionable tasks: 5 executed

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/XXXX/tools/git/react-native-omh-storage/apps/sample-app/android/app/build.gradle' line: 86

* What went wrong:
A problem occurred evaluating project ':app'.
> /Users/XXXXX/tools/git/react-native-omh-storage/apps/sample-app/android/local.properties (No such file or directory)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 14s
info Run CLI with --verbose flag for more details.
```

This error is relatively straightforward for developers who are already familiar with `android-omh-auth` and have experience working with Android projects. However, we should not assume that every developer will immediately know how to resolve this issue, as it could lead to confusion and unnecessary friction.

**Suggested Improvements:**

1. **Documentation**: Clearly state in the documentation the importance of setting up the `local.properties` file. Provide detailed instructions on how to create and configure this file, especially for those who may be new to Android development.

2. **Error Messaging**: Consider improving the error messaging to provide more context or a hint that the issue might be related to the missing `local.properties` file. This can help guide developers to the root of the problem more efficiently.

3. **Preventative Measures**: Implement a pre-check or script that verifies the existence of the `local.properties` file before the build process begins. If the file is missing, output a clear message explaining the need for this file and how to create it.

**Additional Notes:**
I understand that the documentation is still being developed, so I hope that these points will be addressed to improve the developer experience. Thanks for your attention to this matter.

**Comment by dzuluaga** [comment]
Thanks, Adam! Looks like these fixes were added after August. The error message and check seem solid now. Should work well, but we’ll watch for any confusion. Appreciate it!

**Comment by adamTrz** [comment]
Closing the issue as it seems to be resolved :)
