### ISSUE TITLE
Security Concerns with debug.keystore and APK Generation

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-storage#55]
## Issue Description

We have identified several security and usability concerns related to the handling of the debug keystore and the APK generation process in our sample app. These issues potentially pose security risks and negatively impact the developer experience.

## Concerns

1. **debug.keystore checked into source code**
   - The `debug.keystore` file is currently checked into the source code repository.
   - This poses a security risk, even for a sample app, as anyone can build another app using the same signature and potentially access the same services in Azure.

2. **APK Generation in GitHub Actions**
   - While using a keystore for APK generation in GitHub Actions is understandable, the current implementation may not follow best practices.
   - Recommendation: Store the keystore as a base64 encoded GitHub Secret and decode it during the GitHub Action execution.

3. **Confusing Instructions in Sample App**
   - The current instructions require developers to change `MICROSOFT_CLIENT_ID` and `MICROSOFT_SIGNATURE_HASH` in `local.properties`.
   - These values should be associated with the developer's Azure app and the signature hash retrieved from their local machine, not from the source code's debug keystore.
   - This has led to confusion and troubleshooting difficulties, as requests are being sent with two different hashes (one from `local.properties` and another from the debug keystore used to sign the APK).

## Impact

- Security vulnerabilities due to exposed keystore.
- Potential misuse of Azure services.
- Poor developer experience, causing frustration and wasted time during setup and troubleshooting.

## Proposed Solutions

1. Remove `debug.keystore` from the source code repository and update the `.gitignore` file accordingly.
2. Implement a secure method for storing and using the keystore in GitHub Actions, such as using base64 encoded GitHub Secrets.
3. Clarify and simplify the instructions in the sample app documentation, emphasizing the correct usage of `local.properties` and explaining the signature hash generation process.
4. Consider implementing a more streamlined setup process that reduces the potential for confusion between local and repository-provided keystores.

## Questions

- Can we implement these changes to address the security risks and improve the developer experience?
- Are there any concerns or potential impacts we should consider before making these changes?
- What is the timeline for addressing these issues?

Please let me know if you need any further information or clarification on these points.

**Comment by adamTrz** [comment]
Hi @dzuluaga 
I've added a CI check to distinguish android builds done locally and with Github Actions. 
You can check out successful build here: 
https://github.com/openmobilehub/react-native-omh-storage/actions/runs/10811047878
