### ISSUE TITLE
The documentation could be improved

### ISSUE THREAD

**Issue by draggie** [openmobilehub/react-native-omh-storage#71]
Currently the API reference for types, methods etc is missing, there is list of possible methods but without further explanation it makes it a bit harder to actually implement. 
I think that general purpose of this library should be enough clear to be a starter for some projects it would be good to have the fields, examples and showcases present in docs, in this topic the OMH Maps seems more advanced

**Comment by adamTrz** [comment]
Hey @draggie - thanks for raising the issue. 
We have a page with descriptions for all available methods [here in Getting Started guide](https://openmobilehub.github.io/react-native-omh-storage/docs/getting-started/#usage)

I will close the issue for now but feel free to reopen if you feel like we need more explanation in docs :-)
