### ISSUE TITLE
Missing GIF Animations for RN OMH Storage

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-storage#83]
I noticed that the GIF animations for the React Native OMH Storage are still missing from our repository. As I requested earlier, these animations are essential for both technical and non-technical audiences to grasp the concept and functionality of OMH Storage effectively.

**Importance:**

- **Visual Aid:** They provide a clear and quick understanding of OMH Storage features.
- **Audience Engagement:** Help engage and educate users across different learning preferences.

Please prioritize creating and adding these animations to the repository and update the documentation accordingly. It's important to address this promptly without needing reminders.

Thank you.

This issue was already raised here:
https://github.com/openmobilehub/android-omh-storage/issues/76

**Comment by adamTrz** [comment]
Hi @dzuluaga 
I think it was fixed with #82 

Closing the issue for now but please feel free to reopen if you feel there's a need to add more visual guidance 👍
